### ISSUE TITLE
Error matching 250 and 254

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#123]
```
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]: Internal Server Error: /datasets/254/recon/
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]: Traceback (most recent call last):
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 34, in inner
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:     response = get_response(request)
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 115, in _get_response
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:     response = self.process_exception_by_middleware(e, request)
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 113, in _get_response
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:   File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/django/views.py", line 87, in sentry_wrapped_callback
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:     return callback(request, *args, **kwargs)
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:   File "/home/macbookpro/whgazetteer-mehdie/datasets/views.py", line 731, in ds_recon
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:     raise e
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:   File "/home/macbookpro/whgazetteer-mehdie/datasets/views.py", line 727, in ds_recon
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:     d2 = DatasetFile.objects.get(dataset_id=p_dataset)
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:   File "/usr/local/lib/python3.9/dist-packages/django/db/models/manager.py", line 82, in manager_method
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:   File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 406, in get
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]:     raise self.model.DoesNotExist(
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]: datasets.models.DatasetFile.DoesNotExist: DatasetFile matching query does not exist.
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]: [DEBUG] task_id is set to d40958b6-eb02-48f6-b145-7462ed2d275f
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]: [DEBUG] task is ready
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]: [DEBUG] task has succeeded with result [{'detail': {'dataset1': ['id', 'title'], 'dataset2': ['id', 'title']}}, 400]
Aug 28 06:55:11 mehdie-gui gunicorn[2901438]: Exception in ds_recon when trying to fetch dataset files for 250 and 0
```

**Comment by tomersagi** [comment]
Problem seems to be related to p_dataset being set to 0. p_dataset is the selected dataset if it is from the public list but the user selected from their own list. 

![MehdieMatching](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/0ba29f01-d480-419e-b440-518a4db8d510)

A problem was isolated in the error reporting mechanism of the ds_recon routine in the views.py file. Now fixed so that error reporting is more meaningful.

**Comment by tomersagi** [comment]
Error seems to be emanating from mehdie-er-service. Issue continued there.
