### ISSUE TITLE
Recon task loading to database fails

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#126]
```
[2023-09-06 05:41:41,656: INFO/ForkPoolWorker-1] Task datasets.tasks.run_mehdi_er[dd0d6c27-c93b-4b76-9609-149e23b8a9bb] succeeded in 67.2363086938858s: ('https://storage.googleapis.com/mehdie_er/output_b151558d-fb65-47c8-a4d9-164b14daa22f.csv', 200)
[2023-09-06 05:41:41,848: INFO/ForkPoolWorker-2] creating HITS from task_id: 77c7f53b-3d51-4773-afc7-4bd4c285e190
[2023-09-06 05:41:41,893: ERROR/ForkPoolWorker-2] Task align_match_data[77c7f53b-3d51-4773-afc7-4bd4c285e190] raised unexpected: ValueError("could not convert string to float: 'Phonetic title similarity over threshold 0.87 (confidence: 0.9027777778)'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/macbookpro/whgazetteer-mehdie/datasets/tasks.py", line 904, in align_match_data
    hit = Hit.objects.create(
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 910, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1376, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1318, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1319, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1319, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1260, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/fields/__init__.py", line 793, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/fields/__init__.py", line 788, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/fields/__init__.py", line 1743, in get_prep_value
    return float(value)
ValueError: could not convert string to float: 'Phonetic title similarity over threshold 0.87 (confidence: 0.9027777778)'
```

**Comment by tomersagi** [comment]
Bug was caused by mehdie-er service changing the order of the csv file. Fixed.

**Comment by tomersagi** [comment]
New error:
```
[2023-09-06 07:46:58,479: ERROR/ForkPoolWorker-1] Task datasets.tasks.run_mehdi_er[80daad56-7e81-4513-a7e6-099950ad1d2c] raised unexpected: InvalidJSONError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/macbookpro/whgazetteer-mehdie/datasets/tasks.py", line 294, in run_mehdi_er
    csv_url, status_code = mehdi_er(dt_1, dt_2, ds_id, aug_geom, language, userid, match_config)
  File "/home/macbookpro/whgazetteer-mehdie/datasets/tasks.py", line 96, in mehdi_er
    tsv_url = response.json()["csv download url"]
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.InvalidJSONError: Expecting value: line 1 column 1 (char 0)
```

**Comment by tomersagi** [comment]
New error:

```
Task align_match_data[5a42c2b2-d851-420b-bea4-93c43401aac3] raised unexpected: DataError('invalid input syntax for type json\nLINE 1: ...d" = \'dig00801\', "relation_type" = NULL, "json" = \'{"place_i...\n                                                             ^\nDETAIL:  Token "NaN" is invalid.\nCONTEXT:  JSON data, line 1: ...d": "dig00801", "ds": "md"}], "tsv_variants": NaN...\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type json
LINE 1: ...d" = 'dig00801', "relation_type" = NULL, "json" = '{"place_i...
                                                             ^
DETAIL:  Token "NaN" is invalid.
CONTEXT:  JSON data, line 1: ...d": "dig00801", "ds": "md"}], "tsv_variants": NaN...


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/macbookpro/whgazetteer-mehdie/datasets/tasks.py", line 925, in align_match_data
    hit.save()
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 780, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 853, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/base.py", line 903, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/query.py", line 760, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1471, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.9/dist-packages/django/db/models/sql/compiler.py", line 1142, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/django/__init__.py", line 577, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: invalid input syntax for type json
LINE 1: ...d" = 'dig00801', "relation_type" = NULL, "json" = '{"place_i...
                                                             ^
DETAIL:  Token "NaN" is invalid.
CONTEXT:  JSON data, line 1: ...d": "dig00801", "ds": "md"}], "tsv_variants": NaN...
```

**Comment by tomersagi** [comment]
The problem seems to be in the JSON but maybe also in the NaN value for some of the tsv_variants. Needs further investigation.

**Comment by tomersagi** [comment]
Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi result = await app( # type: ignore[func-returns-value] File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__ return await self.app(scope, receive, send) File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__ await super().__call__(scope, receive, send) File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__ await self.middleware_stack(scope, receive, send) File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__ raise exc File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__ await self.app(scope, receive, _send) File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 75, in __call__ raise exc File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 64, in __call__ await self.app(scope, receive, sender) File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__ raise e File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__ await self.app(scope, receive, send) File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 680, in __call__ await route.handle(scope, receive, send) File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 275, in handle await self.app(scope, receive, send) File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app response = await func(request) File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app raw_response = await run_endpoint_function( File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function return await dependant.call(**values) File "/app/main.py", line 103, in create_upload_csv data = aggregate_match_result(logic.match(df1, df2, threshold, phonetic_threshold, max_distance_km)) File "/app/logic.py", line 243, in match block_results = [block_future.result() for block_future in block_futures] File "/app/logic.py", line 243, in <listcomp> block_results = [block_future.result() for block_future in block_futures] File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result return self.__get_result() File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result raise self._exception File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/app/logic.py", line 166, in process_block chunk_results = [chunk_future.result() for chunk_future in chunk_futures] File "/app/logic.py", line 166, in <listcomp> chunk_results = [chunk_future.result() for chunk_future in chunk_futures] File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result return self.__get_result() File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result raise self._exception File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/app/utils.py", line 70, in send_data_to_service response.raise_for_status() File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://mehdi-er-compare-snlwejaxvq-ez.a.run.app/process

**Comment by tomersagi** [comment]
Problem is in the compare service returning 500 sometimes.
