### ISSUE TITLE
Matching review bugged

### ISSUE THREAD

**Issue by sinairusinek** [UHaifa-IS/whgazetteer-mehdie#137]
When matching a dataset ( Yaqut with Usaybie) we have downloadable results but clicking on "review" leads to an error:
![Uploading Screen Shot 2023-10-30 at 12.17.23.png…]()

**Comment by tomersagi** [comment]
The problem appears to be in the creation of the place links. The task was completed , there are results in the hits table. But no place_links. Here is the log from the GUI:

```
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]: Internal Server Error: /datasets/256/review/3d54b516-8eac-42db-8526-17c02b600777/pass1
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]: Traceback (most recent call last):
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 34, in inner
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:     response = get_response(request)
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 115, in _get_response
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:     response = self.process_exception_by_middleware(e, request)
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 113, in _get_response
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:   File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/django/views.py", line 87, in sentry_wrapped_callback
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:     return callback(request, *args, **kwargs)
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:   File "/home/macbookpro/whgazetteer-mehdie/datasets/views.py", line 430, in review
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:     other_place: Place = Place.objects.get(id=hit.get_other_place().id)
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]: AttributeError: 'NoneType' object has no attribute 'id'
Oct 30 10:07:48 mehdie-gui gunicorn[3719970]:  - - [30/Oct/2023:10:07:48 +0000] "GET /datasets/256/review/3d54b516-8eac-42db-8526-17c02b600777/pass1 HTTP/1.0" 500 81218 "https://tool.mehdie.org/datasets/256/reconcile" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]: Internal Server Error: /datasets/256/review/3d54b516-8eac-42db-8526-17c02b600777/pass1
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]: Traceback (most recent call last):
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/exception.py", line 34, in inner
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]:     response = get_response(request)
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 115, in _get_response
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]:     response = self.process_exception_by_middleware(e, request)
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]:   File "/usr/local/lib/python3.9/dist-packages/django/core/handlers/base.py", line 113, in _get_response
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]:   File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/django/views.py", line 87, in sentry_wrapped_callback
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]:     return callback(request, *args, **kwargs)
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]:   File "/home/macbookpro/whgazetteer-mehdie/datasets/views.py", line 430, in review
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]:     other_place: Place = Place.objects.get(id=hit.get_other_place().id)
Oct 30 10:14:34 mehdie-gui gunicorn[3719970]: AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by tomersagi** [comment]
The problem comes from the get_other_place in the hits object returning a None object:

```
    def get_other_place(self):
        if self.authority.isdigit():
            try:
                dataset_label = Dataset.objects.get(id=int(self.authority)).label
                related_place = Place.objects.get(dataset=dataset_label, src_id=self.authrecord_id)
                return related_place
            except (Dataset.DoesNotExist, Place.DoesNotExist):
                return None
        return None
```
That problem is caused by this code failing due to the fact that the authority field in the hits table has 'md' set instead of the integer code representing the other dataset. This is happening when the result of the ER process is converted into hits in tasks.py file, line 906:

```
 hit = Hit.objects.create(
            authority='md',
            authrecord_id=data[1],
            dataset=dataset,
            place=place,
            task_id=task_id,
            query_pass='pass1',
            json=normalize(qobj, qobj['type'], language),
```

**Comment by tomersagi** [comment]
This is all traced back to a problem with the Aladag place IDs which have been loaded as decimals for some reason. 
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/5e29a467-0559-4016-ba31-ecdb61fe3740)
