### ISSUE TITLE
TSV format dataset summary file not downloading

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#152]
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/d40b61fd-f274-41d7-96ab-f05fc46d45ff)

**Comment by tomersagi** [comment]
Error emanates from make_download celery task:

```
[2024-01-11 10:19:56,680: WARNING/ForkPoolWorker-1] make_download() creating download file...
[2024-01-11 10:19:57,635: ERROR/ForkPoolWorker-1] Task make_download[81332ba8-4f10-4641-9f8d-4b8b172d1e6f] raised unexpected: TypeError('sequence item 0: expected str instance, int found')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.9/dist-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/macbookpro/whgazetteer-mehdie/datasets/tasks.py", line 221, in make_download
    links = (';').join(
TypeError: sequence item 0: expected str instance, int found
```
