### ISSUE TITLE
File download not working

### ISSUE THREAD

**Issue by tomersagi** [UHaifa-IS/whgazetteer-mehdie#190]
![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/873aea57-2d0e-40b2-835f-0ac4578162eb)

Leads to undefined.htm.

While you are there check if it exports internal matches as dsid:pid or something else. Should be DS_Label:src_id.

**Comment by tomersagi** [comment]
```
Received task: make_download[eb61f230-df98-419c-a64e-253d9eb02d72]
[2024-06-18 16:54:41,951: WARNING/ForkPoolWorker-3] make_download() creating download file...
[2024-06-18 16:54:42,007: ERROR/ForkPoolWorker-3] Task make_download[eb61f230-df98-419c-a64e-253d9eb02d72] raised unexpected: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/celery.py", line 207, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/_compat.py", line 60, in reraise
    raise value
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/celery.py", line 202, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/user/whgazetteer-mehdie/datasets/tasks.py", line 196, in make_download
    csvfile = open(fn, 'w', newline='', encoding='utf-8')
PermissionError: [Errno 13] Permission denied: '/home/user/whgazetteer-mehdie/media/downloads/tomer-aau_TudelaNotes_20240618_165441.tsv'

```

**Comment by tomersagi** [comment]
Fixed. But it does return 315:159730

**Comment by tomersagi** [comment]
Now returning label:src_id

![image](https://github.com/UHaifa-IS/whgazetteer-mehdie/assets/8471397/5a7721c6-6feb-4bf5-9264-d15a9578a6a2)
